FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    libsndfile1 \
    libsndfile1-dev \
    git \
    build-essential \
    cmake \
    pkg-config \
    protobuf-compiler \
    libprotobuf-dev \
    libffi-dev \
    libssl-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN python -m pip install --no-cache-dir -U pip wheel setuptools

# Torch CPU
RUN python -m pip install --no-cache-dir \
  --index-url https://download.pytorch.org/whl/cpu \
  torch==2.2.2 torchaudio==2.2.2

RUN python -m pip install --no-cache-dir -U pip wheel setuptools \
&& python -m pip install --no-cache-dir "numpy==1.26.4" "Cython>=3.0.8"

COPY nemo/requirements.txt /app/requirements.txt
RUN python -m pip install --no-cache-dir -r /app/requirements.txt

COPY nemo/api.py /app/api.py
COPY nemo/worker.py /app/worker.py
COPY nemo/diarization.yaml /app/diarization.yaml

RUN mkdir -p /data/in /data/out

EXPOSE 8000